const PERMISSIONS = {
  USER_ADMIN: 'USER_ADMIN',
  EVENTS_ADMIN: 'EVENTS_ADMIN',
  GEAR_ADMIN: 'GEAR_ADMIN',

  EVENT_MANAGER: 'EVENT_MANAGER',

  GEAR_MANAGER: 'GEAR_MANAGER',
}

export default PERMISSIONS;
